### ISSUE TITLE
cannot import name YoutubeIE

### ISSUE THREAD

**Issue by icougil** [nonsleepr/edu_10gen_dl#12]
Hi!

I'm actully trying your script, with the latest version of youtube_dl and seems it doesn't work. 

:edu_10gen_dl $ python edx_dl.py ../videos 
Traceback (most recent call last):
  File "edx_dl.py", line 16, in <module>
    from youtube_dl.InfoExtractors  import YoutubeIE
ImportError: cannot import name YoutubeIE

Cheers,

**Comment by gtjemwa** [comment]
cougil,

InfoExtractors is provided for legacy reasons. Replace the offending line 16 with

from youtube_dl.extractor import YoutubeIE

Note however, there is an issue with the arguments to FileDownloader later. See issue#13 that I posted.

**Comment by gtjemwa** [comment]
In fact, there is a patch to this...see issue#9.

**Comment by n1cholasv** [comment]
On OS X the patch works great and only requires 3 lines to be updated in one file.

**Comment by icougil** [comment]
Thx, it works! ;-)
