### ISSUE TITLE
It is possible to download videos with embedded subtitles?

### ISSUE THREAD

**Issue by fgalan** [nonsleepr/edu_10gen_dl#4]
It seems that default execution (`python edu_10gen.py`) download videos without subtitles. It will be great (for not-english natives) to have the ability to download with subtitles.

I have seen in `ydl_params.json` a `subtitleslang` attribute. Is it somehow related with this?

Thanks!

**Comment by fgalan** [comment]
I have tested a bit with `ydl_params.json` using the following:

```
{
...
"subtitleslang": "en",
...
"writesubtitles": true,
...
}
```

You can get an .srt with the subttiles along with the usual .mp4 files. It is not exaclty the same that I mentioned in this issue body (to embed subtitles in the .mp4 file), but it is also ok :)

I would suggest to include this valuable piece of information should be included in the README.md of the repository.

**Comment by nonsleepr** [comment]
Mentioned this option in README. Hope, that's enough.
