### ISSUE TITLE
Cannot download videos - Not all the nessesary libs are installed

### ISSUE THREAD

**Issue by chandaraprakash** [nonsleepr/edu_10gen_dl#5]
When I run the script python edu_10gen.py I get this error : Not all the nessesary libs are installed. Please see requirements.txt.

**Comment by EslamElHusseiny** [comment]
check the following libraries : 
1- python-mechanize
2- python-bs4
3- python-beautifulsoup

**Comment by nonsleepr** [comment]
Install requirements before running this script:
`pip install mechanize beautifulsoup4`
Also in the last commits I've removed youtube_dl code, so, new dependency was added, to resolve it:
`pip install youtube_dl`
