### ISSUE TITLE
Downloader script possibly pointing to the wrong url

### ISSUE THREAD

**Issue by ccolorado** [nonsleepr/edu_10gen_dl#6]
Hello, when trying the script and I get the following error: 
$ python edu_10gen.py 
Can't sign in

I review the code and the script seems to be trying to download from https://www.edx.org/login , this page returns  a 404 in my browser.
If I print out the exception the error seems consistent.

Output:
$ python edu_10gen.py 
HTTP Error 404: Not Found
Can't sign in

Code change :
--- a/edu_10gen.py
+++ b/edu_10gen.py
@@ -90,6 +90,7 @@ class TenGenBrowser(object):
                 print login_state.get('value')
             return self._logged_in
         except mechanize.HTTPError, e:
- ```
         print e
       sys.exit('Can\'t sign in')
  ```
  
   def list_courses(self):

**Comment by nonsleepr** [comment]
You should put `courses.edx.org` as DOMAIN instead of `www.edx.org`.

**Comment by ccolorado** [comment]
Would you consider appropriate listing compatible websites that the script is intended for ? 

My reasoning is that if I hadn't contacted you I would still be thinking that edx.org was where education.10gen.com stored it's content and probably would had tried the correct one. 

Regards

**Comment by nonsleepr** [comment]
Not sure if my last commit will fix this, since I don't have edx account.
